### ISSUE TITLE
建议使用https请求

### ISSUE THREAD

**Issue by legends-killer** [DevHexgram/Schedule_management_back_end#2]
现在只能通过http://www.xxxx.com:1221请求后台，https无法完成请求，希望能改为https请求。

**Comment by XMLHexagram** [comment]
现在可以通过`https://xxxxx.com`请求原本的`1221`

例如: `https://xxxxx.com/backgroundImage`

无需加上端口,会自动转发到对应的`1221`端口上

但是受制于资金(免费的https只能管两个域名),现在只有`1221`端口,也就是生产环境,可以使用https
